name: smart_body_life
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: 6.3.1
  http: ^1.2.2 
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: 0.19.0
  image_picker: ^1.0.0

  # ИИ-ЗРЕНИЕ (Распознаем еду и цветы по фото)
  google_mlkit_commons: ^0.6.1
  google_mlkit_object_detection: ^0.11.0 
  tflite_flutter: ^0.12.1 
  
  # МУЛЬТИМЕДИА
  video_player: 2.4.5
  
  # ЗДОРОВЬЕ И АНАЛИТИКА
  health: 8.0.0
  permission_handler: ^12.0.1
  fl_chart: ^0.69.2
  
  # КАЛЕНДАРЬ (Версия 4.3.1 для фикса ошибки Namespace)
 
  flutter_timezone: ^5.0.2

  # ХРАНЕНИЕ ДАННЫХ
  path_provider: ^2.1.5
  sqflite: ^2.3.0

  # СИСТЕМНЫЕ УТИЛИТЫ
  collection: ^1.18.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - ui_images/   
    - res_gym/
    - avatars/
    - instructions/
    - images/
    - videos/
    - item_male/icons/
    - item_female/icons/
    - item_male/layers/
    - item_female/layers/
    - assets/sounds/
    - assets/images/soups/
    - assets/images/salads/
    - assets/images/mains/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "ui_images/icon.png"
  adaptive_icon_background: "#001A10"
  adaptive_icon_foreground: "ui_images/icon.png"

dependency_overrides:
  intl: 0.19.0