name: smart_body_life
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: 6.3.1
  http: ^1.2.2 
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: 0.19.0
  image_picker: ^1.0.0

  google_mlkit_commons: ^0.6.1
  mobile_scanner: 3.5.2    # ГЛАЗА: Сканирует сам штрих-кod через камеру
  openfoodfacts: ^3.25.0    # МОЗГИ: Ищет этот код в мировой базе продуктов
  google_mlkit_object_detection: ^0.11.0 # <--- Добавили для распознавания объектов в кадре
  google_mlkit_barcode_scanning: ^0.10.0 # <--- Добавили для сканирования штрих-кodов
  
  #camera: 0.10.5+9  # <--- ГЛАЗА: Живое видео для сканера 📸
  tflite_flutter: ^0.12.1 # <--- МОЗГИ: Чтобы запускать TensorFlow Lite прямо на ноутбуке 🧠
  # ВИДЕО ПЛЕЕР 🎬 (Добавили для живого аватара)
  video_player: 2.4.5
  audioplayers: ^6.1.0  # <--- Добавь вот это
  # ЗДОРОВЬЕ: Самые свежие версии для "Магнита" 💎
  health: 10.1.0
  permission_handler: ^12.0.1

  # ГРАФИКИ: Версия 0.70.0 — самая мощная для новых iPhone
  fl_chart: ^0.69.2
  
  # КАЛЕНДАРЬ
  add_2_calendar: ^3.0.1
  
  # ПАМЯТЬ И БАЗА ДАННЫХ
  path_provider: ^2.1.5
  sqflite: ^2.3.0

  # ИНСТРУМЕНТЫ И ПЕРЕВОД
  google_mlkit_translation: ^0.9.0
  collection: ^1.18.0
  path: ^1.9.0
  google_fonts: ^6.2.1

# УВЕДОМЛЕНИЯ И ВРЕМЯ 🔔
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  flutter_timezone: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true

  assets:
    - ui_images/   
    - res_gym/
    - avatars/
    - instructions/
    - images/
    - videos/
    - item_male/icons/
    - item_female/icons/
    - item_male/layers/
    - item_female/layers/
    - assets/sounds/  # <--- Теперь программа знает, где искать дзынь
    - assets/images/soups/
    - assets/images/salads/
    - assets/images/mains/
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "ui_images/icon.png"
  adaptive_icon_background: "#001A10"
  adaptive_icon_foreground: "ui_images/icon.png"

# ДОБАВЬТЕ ЭТО В САМЫЙ КОНЕЦ:
dependency_overrides:
  meta: 1.15.0
