platform :ios, '17.0'

generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
File.foreach(generated_xcode_build_settings_path) do |line|
  matches = line.match(/FLUTTER_ROOT\=(.*)/)
  @flutter_root = matches[1].strip if matches
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), @flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Решение для Flutter.framework и плагинов
    if ['device_info_plus', 'url_launcher_ios', 'video_player_avfoundation', 'Flutter'].include?(target.name)
      privacy_path = File.expand_path('Runner/PrivacyInfo.xcprivacy')
      if File.exist?(privacy_path)
        # Создаем ресурсную фазу, которую Xcode обязан подписать
        bundle_target = installer.pods_project.new_target(:bundle, 'PrivacyResources', :ios)
        bundle_target.build_configurations.each { |config| config.build_settings['PRODUCT_NAME'] = 'PrivacyResources' }
        
        file_ref = installer.pods_project.new_file(privacy_path)
        bundle_target.add_resources([file_ref])
        
        # Связываем этот бандл с целью
        target.add_dependency(bundle_target)
      end
    end

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
