platform :ios, '17.0'

# Прямое указание Котику, где лежат инструменты Flutter
# В облаке GitHub путь к SDK всегда доступен через переменную FLUTTER_ROOT
flutter_install_path = ENV['FLUTTER_ROOT']

if flutter_install_path.nil?
  # Если мы на ноутбуке, используем стандартный относительный путь
  flutter_install_path = File.expand_path(File.join('..', '..', 'flutter'), __FILE__)
end

# Подключаем помощник напрямую из движка Flutter
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_install_path)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # Вот эта строчка — ЛЕКАРСТВО. Она принудительно ставит 17.0 
        # для КАЖДОЙ маленькой библиотеки (включая health)
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
        
        config.build_settings['DEVELOPMENT_TEAM'] = 'PCSW3AKAPF'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
  
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
