name: SMART-BODY-LIFE-FINAL-PACKAGE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: 1. ЗАГРУЗКА КОДА
        uses: actions/checkout@v4

      - name: 2. УСТАНОВКА Xcode 26.3
        run: sudo xcode-select -s /Applications/Xcode_26.3.app/Contents/Developer

      - name: 3. УСТАНОВКА FLUTTER 3.29.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: 4. ВОССТАНОВЛЕНИЕ .env ИЗ СЕКРЕТОВ
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "Файл .env готов."

      - name: 5. ОБНОВЛЕНИЕ БИБЛИОТЕК (Для Apple)
        run: |
          flutter pub upgrade device_info_plus url_launcher video_player
          flutter pub get

      - name: 6. УСТАНОВКА ПРОФИЛЯ И БЛОКИРОВКА АВТОМАТИКИ
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_PATH=$(find . -name "SMART_DISTRIBUTION_3.mobileprovision" | head -n 1)
          
          # Копируем профиль в системную папку
          cp "$PROFILE_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/f2e7364b-98c7-44ad-a0dc-84acd2d0fd80.mobileprovision
          
          # ПРИНУДИТЕЛЬНО ПЕРЕПИСЫВАЕМ ФАЙЛ ПРОЕКТА (удаляем любые следы автоматики)
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = \".*\";/PROVISIONING_PROFILE_SPECIFIER = \"SMART_DISTRIBUTION\";/g" ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/PROVISIONING_PROFILE = \".*\";/PROVISIONING_PROFILE = \"f2e7364b-98c7-44ad-a0dc-84acd2d0fd80\";/g" ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/DEVELOPMENT_TEAM = \".*\";/DEVELOPMENT_TEAM = \"PCSW3AKAPF\";/g" ios/Runner.xcodeproj/project.pbxproj

      - name: 7. ОКОНЧАТЕЛЬНАЯ СБОРКА
        run: |
          # Собираем архив БЕЗ автоматического подписания на этапе Flutter
          # Мы берем управление на себя через export-options-plist
          flutter build ipa --release --no-codesign --dart-define-from-file=.env
          
          # Теперь запускаем упаковку (архивацию) через сам Xcode, где наши настройки уже применены
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/ios/archive/Runner.xcarchive \
                     archive \
                     PROVISIONING_PROFILE="f2e7364b-98c7-44ad-a0dc-84acd2d0fd80" \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES
